sudo: false
language: ruby
rvm:
  - 2.1.10
  - 2.0.0
  - 1.9.3
env:
  - TESTOPTS=-v
gemfile:
  - gemfiles/Gemfile.travis-ruby1.9
before_install:
  - mkdir /tmp/bioruby
  - ruby gemfiles/modify-Gemfile.rb
  - ruby gemfiles/prepare-gemspec.rb
matrix:
  include:
    - rvm: 1.8.7
      gemfile: gemfiles/Gemfile.travis-ruby1.8
      env: TESTOPTS=-v
    - rvm: rbx-3.29
      gemfile: gemfiles/Gemfile.travis-rbx
      env: TESTOPTS=-v
    - rvm: jruby-18mode
      gemfile: gemfiles/Gemfile.travis-jruby1.8
      env: TMPDIR=/tmp/bioruby TESTOPTS=-v
    - rvm: jruby-19mode
      gemfile: gemfiles/Gemfile.travis-jruby1.9
      env: TMPDIR=/tmp/bioruby TESTOPTS=-v
    - rvm: 2.3.1
      gemfile: Gemfile
    - rvm: 2.2.5
      gemfile: Gemfile
    - rvm: 2.2.5
      gemfile: Gemfile
      env: BIORUBY_RAKE_DEFAULT_TASK=tar-integration-test TESTOPTS=-v
    - rvm: 2.2.5
      gemfile: Gemfile
      env: BIORUBY_RAKE_DEFAULT_TASK=gem-test TESTOPTS=-v
    - rvm: jruby-19mode
      gemfile: gemfiles/Gemfile.travis-jruby1.9
      env: TMPDIR=/tmp/bioruby BIORUBY_RAKE_DEFAULT_TASK=tar-integration-test TESTOPTS=-v
    - rvm: jruby-19mode
      gemfile: gemfiles/Gemfile.travis-jruby1.9
      env: TMPDIR=/tmp/bioruby BIORUBY_RAKE_DEFAULT_TASK=gem-test TESTOPTS=-v
  allow_failures:
    - rvm: rbx-3.29
      gemfile: gemfiles/Gemfile.travis-rbx
      env: TESTOPTS=-v
    - rvm: jruby-18mode
      gemfile: gemfiles/Gemfile.travis-jruby1.8
      env: TMPDIR=/tmp/bioruby TESTOPTS=-v
    - rvm: jruby-19mode
      gemfile: gemfiles/Gemfile.travis-jruby1.9
      env: TMPDIR=/tmp/bioruby TESTOPTS=-v
    - rvm: jruby-19mode
      gemfile: gemfiles/Gemfile.travis-jruby1.9
      env: TMPDIR=/tmp/bioruby BIORUBY_RAKE_DEFAULT_TASK=tar-integration-test TESTOPTS=-v
    - rvm: jruby-19mode
      gemfile: gemfiles/Gemfile.travis-jruby1.9
      env: TMPDIR=/tmp/bioruby BIORUBY_RAKE_DEFAULT_TASK=gem-test TESTOPTS=-v

# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec

#before_install:
# - sudo apt-get update
# - sudo apt-get install libxml2-dev libexpat1-dev

# whitelist branches
branches:
  only:
    - master

